module.exports = {
    USER_COLLECTION: process.env.USER_COLLECTION,
    ADMIN_COLLECTION: process.env.ADMIN_COLLECTION,
    CATEGORY_COLLECTION: process.env.CATEGORY_COLLECTION,
    BRAND_COLLECTION: process.env.BRAND_COLLECTION,
    PRODUCT_COLLECTION: process.env.PRODUCT_COLLECTION,
    CART_COLLECTION: process.env.CART_COLLECTION,
    ORDER_COLLECTION: process.env.ORDER_COLLECTION,
    BANNER_COLLECTION: process.env.BANNER_COLLECTION,
    CATEGORY_OFFERS: process.env.CATEGORY_OFFERS,
    PRODUCT_OFFERS: process.env.PRODUCT_OFFERS,
    COUPON_COLLECTION: process.env.COUPON_COLLECTION,
    WISHLIST_COLLECTION: process.env.WISHLIST_COLLECTION
}