module.exports={
    USER_COLLECTION:'User',
    ADMIN_COLLECTION:'Admin',
    CATEGORY_COLLECTION:'Category',
    BRAND_COLLECTION:'Brand',
    PRODUCT_COLLECTION:'Products',
    CART_COLLECTION:'Cart',
    ORDER_COLLECTION:'Order',
    BANNER_COLLECTION:'Banner',
    CATEGORY_OFFERS:'CategoryOffer',
    PRODUCT_OFFERS:'ProductOffer',
    COUPON_COLLECTION:'Coupons',
    WISHLIST_COLLECTION:'Wishlist'
}